const generatedWords = {
    '11-4-2022': 'hørte',
    '12-4-2022': 'bestå',
    '13-4-2022': 'samoa',
    '14-4-2022': 'anlæg',
    '15-4-2022': 'rodet',
    '16-4-2022': 'krone',
    '17-4-2022': 'vente',
    '18-4-2022': 'harly',
    '19-4-2022': 'bluse',
    '20-4-2022': 'jacob',
    '21-4-2022': 'grise',
    '22-4-2022': 'svamp',
    '23-4-2022': 'læses',
    '24-4-2022': 'tæppe',
    '25-4-2022': 'bevis',
    '26-4-2022': 'forum',
    '27-4-2022': 'bilen',
    '28-4-2022': 'adams',
    '29-4-2022': 'opgør',
    '30-4-2022': 'nærer',
    '31-4-2022': 'beløb',
    '1-5-2022': 'brist',
    '2-5-2022': 'været',
    '3-5-2022': 'sjæle',
    '4-5-2022': 'liner',
    '5-5-2022': 'pikke',
    '6-5-2022': 'rubin',
    '7-5-2022': 'grams',
    '8-5-2022': 'lokum',
    '9-5-2022': 'odden',
    '10-5-2022': 'møder',
    '11-5-2022': 'urtid',
    '12-5-2022': 'kujon',
    '13-5-2022': 'banan',
    '14-5-2022': 'ravns',
    '15-5-2022': 'ilder',
    '16-5-2022': 'månen',
    '17-5-2022': 'klavs',
    '18-5-2022': 'mimik',
    '19-5-2022': 'kjeld',
    '20-5-2022': 'levne',
    '21-5-2022': 'porto',
    '22-5-2022': 'bunke',
    '23-5-2022': 'opnår',
    '24-5-2022': 'peber',
    '25-5-2022': 'deler',
    '26-5-2022': 'holte',
    '27-5-2022': 'truck',
    '28-5-2022': 'oktan',
    '29-5-2022': 'fejet',
    '30-5-2022': 'engel',
    '1-6-2022': 'safir',
    '2-6-2022': 'withs',
    '3-6-2022': 'drømt',
    '4-6-2022': 'hobby',
    '5-6-2022': 'tager',
    '6-6-2022': 'løste',
    '7-6-2022': 'bente',
    '8-6-2022': 'teori',
    '9-6-2022': 'deres',
    '10-6-2022': 'komme',
    '11-6-2022': 'tænkt',
    '12-6-2022': 'uheld',
    '13-6-2022': 'konge',
    '14-6-2022': 'orlon',
    '15-6-2022': 'baret',
    '16-6-2022': 'dybet',
    '17-6-2022': 'kunne',
    '18-6-2022': 'vidst',
    '19-6-2022': 'gabon',
    '20-6-2022': 'udfør',
    '21-6-2022': 'evans',
    '22-6-2022': 'brian',
    '23-6-2022': 'claus',
    '24-6-2022': 'ligge',
    '25-6-2022': 'hejre',
    '26-6-2022': 'riger',
    '27-6-2022': 'afsæt',
    '28-6-2022': 'facts',
    '29-6-2022': 'opgør',
    '30-6-2022': 'dreng',
    '31-6-2022': 'båsen',
    '1-7-2022': 'optog',
    '2-7-2022': 'øvede',
    '3-7-2022': 'jeget',
    '4-7-2022': 'mille',
    '5-7-2022': 'vokse',
    '6-7-2022': 'blank',
    '7-7-2022': 'fokus',
    '8-7-2022': 'lyset',
    '9-7-2022': 'rabat',
    '10-7-2022': 'peget',
    '11-7-2022': 'ældes',
    '12-7-2022': 'vrøvl',
    '13-7-2022': 'temas',
    '14-7-2022': 'balje',
    '15-7-2022': 'plast',
    '16-7-2022': 'gaven',
    '17-7-2022': 'score',
    '18-7-2022': 'udkig',
    '19-7-2022': 'anset',
    '20-7-2022': 'vogte',
    '21-7-2022': 'siden',
    '22-7-2022': 'kofte',
    '23-7-2022': 'skrig',
    '24-7-2022': 'lærde',
    '25-7-2022': 'høres',
    '26-7-2022': 'skære',
    '27-7-2022': 'higen',
    '28-7-2022': 'bonus',
    '29-7-2022': 'kodet',
    '30-7-2022': 'åbent',
    '31-7-2022': 'stave',
    '1-8-2022': 'pinde',
    '2-8-2022': 'hvori',
    '3-8-2022': 'styre',
    '4-8-2022': 'herpå',
    '5-8-2022': 'råber',
    '6-8-2022': 'pløje',
    '7-8-2022': 'safir',
    '8-8-2022': 'bunds',
    '9-8-2022': 'skråt',
    '10-8-2022': 'arves',
    '11-8-2022': 'klare',
    '12-8-2022': 'afkom',
    '13-8-2022': 'sigte',
    '14-8-2022': 'rings',
    '15-8-2022': 'ascii',
    '16-8-2022': 'pløje',
    '17-8-2022': "pc'er",
    '18-8-2022': 'tuber',
    '19-8-2022': 'hidse',
    '20-8-2022': 'poesi',
    '21-8-2022': 'novra',
    '22-8-2022': 'megen',
    '23-8-2022': 'juice',
    '24-8-2022': 'bakke',
    '25-8-2022': 'værre',
    '26-8-2022': 'lynne',
    '27-8-2022': 'afled',
    '28-8-2022': 'fejle',
    '29-8-2022': 'noter',
    '30-8-2022': 'brudt',
    '1-9-2022': 'satse',
    '2-9-2022': 'pigen',
    '3-9-2022': 'gaden',
    '4-9-2022': 'viril',
    '5-9-2022': 'stand',
    '6-9-2022': 'patte',
    '7-9-2022': 'brian',
    '8-9-2022': 'andre',
    '9-9-2022': 'psyke',
    '10-9-2022': 'optog',
    '11-9-2022': 'bruge',
    '12-9-2022': 'jimmy',
    '13-9-2022': 'hunde',
    '14-9-2022': 'bacon',
    '15-9-2022': 'faste',
    '16-9-2022': 'ugers',
    '17-9-2022': 'bager',
    '18-9-2022': 'mille',
    '19-9-2022': 'danne',
    '20-9-2022': 'sange',
    '21-9-2022': 'kolon',
    '22-9-2022': 'palle',
    '23-9-2022': 'pause',
    '24-9-2022': 'siger',
    '25-9-2022': 'bytte',
    '26-9-2022': 'broer',
    '27-9-2022': 'nonne',
    '28-9-2022': 'timer',
    '29-9-2022': 'sagde',
    '30-9-2022': 'lokal',
    '31-9-2022': 'dyrke',
    '1-10-2022': 'holdt',
    '2-10-2022': 'komma',
    '3-10-2022': 'infam',
    '4-10-2022': 'heder',
    '5-10-2022': 'syren',
    '6-10-2022': 'skala',
    '7-10-2022': 'gnide',
    '8-10-2022': 'dække',
    '9-10-2022': 'bacon',
    '10-10-2022': 'moral',
    '11-10-2022': 'sagde',
    '12-10-2022': 'trane',
    '13-10-2022': 'klare',
    '14-10-2022': 'lyrik',
    '15-10-2022': 'skrap',
    '16-10-2022': 'titel',
    '17-10-2022': 'vippe',
    '18-10-2022': 'balke',
    '19-10-2022': 'palle',
    '20-10-2022': 'tætte',
    '21-10-2022': 'dværg',
    '22-10-2022': 'udgav',
    '23-10-2022': 'anton',
    '24-10-2022': 'læser',
    '25-10-2022': 'khmer',
    '26-10-2022': 'minut',
    '27-10-2022': 'gøres',
    '28-10-2022': 'kløft',
    '29-10-2022': 'byens',
    '30-10-2022': 'fiber',
    '1-11-2022': 'svæve',
    '2-11-2022': 'pinse',
    '3-11-2022': 'elven',
    '4-11-2022': 'ankom',
    '5-11-2022': 'david',
    '6-11-2022': 'anslå',
    '7-11-2022': 'episk',
    '8-11-2022': 'glimt',
    '9-11-2022': 'mette',
    '10-11-2022': 'skive',
    '11-11-2022': 'udgør',
    '12-11-2022': 'lokal',
    '13-11-2022': 'vinen',
    '14-11-2022': 'mødes',
    '15-11-2022': 'beløb',
    '16-11-2022': 'snyde',
    '17-11-2022': 'aksel',
    '18-11-2022': 'opsig',
    '19-11-2022': 'spørg',
    '20-11-2022': 'siges',
    '21-11-2022': 'gøsta',
    '22-11-2022': 'udfri',
    '23-11-2022': 'enten',
    '24-11-2022': 'alfer',
    '25-11-2022': 'forbi',
    '26-11-2022': 'rykke',
    '27-11-2022': 'uhyre',
    '28-11-2022': 'beses',
    '29-11-2022': 'vækst',
    '30-11-2022': 'moden',
    '31-11-2022': 'ajour',
    '1-0-2023': 'efter',
    '2-0-2023': 'ældes',
    '3-0-2023': 'fibre',
    '4-0-2023': 'ulige',
    '5-0-2023': 'tumle',
    '6-0-2023': 'møder',
    '7-0-2023': 'klaus',
    '8-0-2023': 'hører',
    '9-0-2023': 'bløde',
    '10-0-2023': 'allan',
    '11-0-2023': 'rører',
    '12-0-2023': 'gurli',
    '13-0-2023': 'medio',
    '14-0-2023': 'dyder',
    '15-0-2023': 'faren',
    '16-0-2023': 'betty',
    '17-0-2023': 'skjul',
    '18-0-2023': 'skabt',
    '19-0-2023': 'binde',
    '20-0-2023': 'visne',
    '21-0-2023': 'drømt',
    '22-0-2023': 'tabet',
    '23-0-2023': 'bolde',
    '24-0-2023': 'kendt',
    '25-0-2023': 'smøre',
    '26-0-2023': 'skole',
    '27-0-2023': 'fugle',
    '28-0-2023': 'alene',
    '29-0-2023': 'skarp',
    '30-0-2023': 'macro',
    '31-0-2023': 'røget',
    '1-1-2023': 'runes',
    '2-1-2023': 'kbyte',
    '3-1-2023': 'yndig',
    '4-1-2023': 'ovale',
    '5-1-2023': 'plane',
    '6-1-2023': 'langt',
    '7-1-2023': 'heppe',
    '8-1-2023': 'farum',
    '9-1-2023': 'vasal',
    '10-1-2023': 'stænk',
    '11-1-2023': 'fylde',
    '12-1-2023': 'bruge',
    '13-1-2023': 'sankt',
    '14-1-2023': 'nørre',
    '15-1-2023': 'fyldt',
    '16-1-2023': 'papir',
    '17-1-2023': 'dræbe',
    '18-1-2023': 'kræft',
    '19-1-2023': 'polet',
    '20-1-2023': 'enten',
    '21-1-2023': 'syren',
    '22-1-2023': 'dyder',
    '23-1-2023': 'vasal',
    '24-1-2023': 'skyld',
    '25-1-2023': 'bager',
    '26-1-2023': 'borum',
    '27-1-2023': 'klage',
    '28-1-2023': 'hæver',
    '1-2-2023': 'brunt',
    '2-2-2023': 'begik',
    '3-2-2023': 'nobel',
    '4-2-2023': 'plage',
    '5-2-2023': 'ville',
    '6-2-2023': 'lager',
    '7-2-2023': 'udbud',
    '8-2-2023': 'kolde',
    '9-2-2023': 'finde',
    '10-2-2023': 'skriv',
    '11-2-2023': 'hængt',
    '12-2-2023': 'oscar',
    '13-2-2023': 'mette',
    '14-2-2023': 'simon',
    '15-2-2023': 'sjæle',
    '16-2-2023': 'taste',
    '17-2-2023': 'svagt',
    '18-2-2023': 'rørby',
    '19-2-2023': 'vente',
    '20-2-2023': 'røver',
    '21-2-2023': 'hvede',
    '22-2-2023': 'firer',
    '23-2-2023': 'odder',
    '24-2-2023': 'altre',
    '25-2-2023': 'siges',
    '26-2-2023': 'tokyo',
    '27-2-2023': 'bille',
    '28-2-2023': 'pines',
    '29-2-2023': 'sinde',
    '30-2-2023': 'hylde',
    '31-2-2023': 'bisag',
    '1-3-2023': 'køber',
    '2-3-2023': 'hindu',
    '3-3-2023': 'hvalp',
    '4-3-2023': 'facon',
    '5-3-2023': 'ideen',
    '6-3-2023': 'kæder',
    '7-3-2023': 'affyr',
    '8-3-2023': 'strip',
    '9-3-2023': 'trone',
    '10-3-2023': 'påkær',
    '11-3-2023': 'bænke',
    '12-3-2023': 'guden',
    '13-3-2023': 'maske',
    '14-3-2023': 'clark',
    '15-3-2023': 'iltet',
    '16-3-2023': 'lurer',
    '17-3-2023': 'hævne',
    '18-3-2023': 'sines',
    '19-3-2023': 'flyve',
    '20-3-2023': 'afløb',
    '21-3-2023': 'gange',
    '22-3-2023': 'fulgt',
    '23-3-2023': 'tider',
    '24-3-2023': 'kakao',
    '25-3-2023': 'timen',
    '26-3-2023': 'usand',
    '27-3-2023': 'vores',
    '28-3-2023': 'hadet',
    '29-3-2023': 'drama',
    '30-3-2023': 'hoppe',
    '1-4-2023': 'vejer',
    '2-4-2023': 'drage',
    '3-4-2023': 'essay',
    '4-4-2023': 'plade',
    '5-4-2023': 'skøde',
    '6-4-2023': 'siver',
    '7-4-2023': 'stærk',
    '8-4-2023': 'skyld',
    '9-4-2023': 'atter',
    '10-4-2023': 'søren',
};
const availableWords = [
    'abbed',
    'abort',
    'acres',
    'adams',
    'adlet',
    'adlyd',
    'adlød',
    'adolf',
    'adræt',
    'advar',
    'advis',
    'afart',
    'afbød',
    'afdød',
    'affyr',
    'afgav',
    'afgiv',
    'afgud',
    'afgør',
    'afkom',
    'afled',
    'afløb',
    'afløs',
    'afsat',
    'afslå',
    'afstå',
    'afsæt',
    'aftal',
    'aften',
    'afveg',
    'agent',
    'agnen',
    'agnes',
    'agter',
    'agtig',
    'ahorn',
    'aires',
    'ajour',
    'aksel',
    'aksen',
    'akser',
    'aktie',
    'aktiv',
    'alarm',
    'album',
    'alder',
    'aldre',
    'alene',
    'alfer',
    'algol',
    'alias',
    'alice',
    'allan',
    'aller',
    'alles',
    'almas',
    'almen',
    'almue',
    'alter',
    'altet',
    'altid',
    'altre',
    'altså',
    'alvor',
    'andel',
    'anden',
    'andet',
    'andre',
    'angiv',
    'angst',
    'angår',
    'anker',
    'ankom',
    'ankre',
    'anlæg',
    'annes',
    'annie',
    'ansat',
    'anser',
    'anses',
    'anset',
    'anslå',
    'ansæt',
    'ansås',
    'antag',
    'antal',
    'antog',
    'anton',
    'appel',
    'april',
    'araen',
    'areal',
    'arena',
    'argon',
    'arhus',
    'arier',
    'arket',
    'arkiv',
    'armen',
    'arrak',
    'arten',
    'arter',
    'arven',
    'arver',
    'arves',
    'ascii',
    'asger',
    'asien',
    'asken',
    'athen',
    'atlas',
    'atoms',
    'atten',
    'atter',
    'avler',
    'baard',
    'bachs',
    'bacon',
    'bager',
    'bagom',
    'bajer',
    'bakke',
    'bakse',
    'balde',
    'balje',
    'balke',
    'balle',
    'bamse',
    'banal',
    'banan',
    'bande',
    'bandt',
    'banen',
    'baner',
    'bange',
    'banjo',
    'banke',
    'banko',
    'barde',
    'baren',
    'baret',
    'barok',
    'baron',
    'barry',
    'baser',
    'basic',
    'basis',
    'bebos',
    'beder',
    'bedes',
    'bedre',
    'bedst',
    'befri',
    'begge',
    'begik',
    'behov',
    'beløb',
    'benny',
    'bente',
    'benyt',
    'beror',
    'besad',
    'beses',
    'bestå',
    'besøg',
    'beton',
    'betty',
    'betød',
    'bevar',
    'bevis',
    'bevæg',
    'bibel',
    'bider',
    'bifag',
    'bilag',
    'biled',
    'bilen',
    'biler',
    'bille',
    'billy',
    'binde',
    'binær',
    'birte',
    'bisag',
    'bison',
    'bizar',
    'bjerg',
    'bjørn',
    'blade',
    'bland',
    'blank',
    'blidt',
    'blind',
    'blink',
    'blitz',
    'blive',
    'bloks',
    'blond',
    'bluse',
    'blære',
    'blæse',
    'bløde',
    'blødt',
    'boble',
    'bodil',
    'bogen',
    'bokse',
    'bolde',
    'bolig',
    'bolte',
    'bomme',
    'bonde',
    'bonus',
    'bopæl',
    'borde',
    'bords',
    'borge',
    'boris',
    'borte',
    'borum',
    'borup',
    'bowle',
    'bragt',
    'brand',
    'brase',
    'brave',
    'brede',
    'bredt',
    'breve',
    'brian',
    'brint',
    'brise',
    'brist',
    'britt',
    'broen',
    'broer',
    'brudt',
    'bruge',
    'brugt',
    'brune',
    'brunt',
    'bruse',
    'bruun',
    'bryde',
    'bryst',
    'brønd',
    'bulle',
    'bunds',
    'bundt',
    'bunke',
    'burde',
    'burma',
    'buske',
    'butik',
    'byder',
    'byens',
    'bygge',
    'byrde',
    'bytes',
    'bytte',
    'bælte',
    'bænke',
    'bærer',
    'bæres',
    'bøger',
    'bøjer',
    'bølge',
    'bønne',
    'børns',
    'børre',
    'båden',
    'båret',
    'båsen',
    'cairo',
    'carte',
    'celle',
    'cerut',
    'check',
    'chile',
    'chips',
    'chris',
    'cifre',
    'cigar',
    'citat',
    'civil',
    'clark',
    'claus',
    'cobol',
    'comal',
    'costa',
    'creme',
    'cykel',
    'cykle',
    'cæsar',
    'dagen',
    'dages',
    'daimi',
    'dalen',
    'damer',
    'dampe',
    'danbo',
    'danne',
    'danse',
    'dansk',
    'david',
    'debat',
    'debut',
    'dejse',
    'delen',
    'deler',
    'deles',
    'delta',
    'delte',
    'denne',
    'depot',
    'deraf',
    'deres',
    'derpå',
    'desto',
    'dette',
    'digte',
    'dines',
    'dingo',
    'dirke',
    'disen',
    'diske',
    'disse',
    'ditto',
    'doble',
    'dolke',
    'dolly',
    'doris',
    'dorte',
    'doser',
    'dosis',
    'doven',
    'dovne',
    'drage',
    'drama',
    'dreje',
    'dreng',
    'drift',
    'drink',
    'drive',
    'druer',
    'dræbe',
    'dræbt',
    'drømt',
    'dukke',
    'dumme',
    'dumps',
    'dusin',
    'dværg',
    'dybde',
    'dybet',
    'dyder',
    'dyner',
    'dynge',
    'dyret',
    'dyrke',
    'dække',
    'dæmon',
    'dæmpe',
    'døden',
    'dødis',
    'dømme',
    'døren',
    'døsig',
    'døtre',
    'dådyr',
    'dåser',
    'edens',
    'edgar',
    'edwin',
    'efter',
    'egner',
    'egnet',
    'eigil',
    'eiler',
    'ejede',
    'ejere',
    'eksem',
    'eksil',
    'elias',
    'elisa',
    'elite',
    'eliza',
    'eller',
    'elovn',
    'elven',
    'elver',
    'elvis',
    'emily',
    'emner',
    'emnet',
    'endda',
    'enden',
    'ender',
    'endnu',
    'endog',
    'endte',
    'enens',
    'engel',
    'engen',
    'engle',
    'enhed',
    'enige',
    'enkel',
    'enkle',
    'enlig',
    'enorm',
    'enten',
    'entre',
    'episk',
    'epoke',
    'ernst',
    'essay',
    'etage',
    'etisk',
    'ettal',
    'evans',
    'evige',
    'evigt',
    'evnen',
    'evner',
    'fabel',
    'facon',
    'facts',
    'fader',
    'fakta',
    'falck',
    'falde',
    'faldt',
    'falme',
    'false',
    'falsk',
    'fandt',
    'fange',
    'faren',
    'farer',
    'farte',
    'farum',
    'farve',
    'fasan',
    'faser',
    'faste',
    'fatal',
    'fatte',
    'faust',
    'favør',
    'feber',
    'fejer',
    'fejet',
    'fejle',
    'femte',
    'ferie',
    'fiber',
    'fibre',
    'fidus',
    'figur',
    'fikse',
    'filen',
    'files',
    'filur',
    'finde',
    'finne',
    'finsk',
    'finte',
    'firer',
    'fires',
    'firma',
    'fiske',
    'fisse',
    'fjern',
    'fjols',
    'flade',
    'flags',
    'flere',
    'flest',
    'flink',
    'flora',
    'flove',
    'flugt',
    'flyde',
    'flyve',
    'flæsk',
    'fløjt',
    'fodre',
    'fokus',
    'folde',
    'folks',
    'foran',
    'forbi',
    'fordi',
    'forel',
    'foren',
    'forme',
    'forud',
    'forum',
    'forår',
    'fosse',
    'fragt',
    'frank',
    'frans',
    'franz',
    'freud',
    'frida',
    'frisk',
    'frist',
    'fritz',
    'frode',
    'front',
    'frost',
    'frugt',
    'frygt',
    'fryse',
    'fråds',
    'fugle',
    'fulde',
    'fuldt',
    'fulgt',
    'fuppe',
    'fylde',
    'fyldt',
    'fyren',
    'fyrer',
    'fyret',
    'fyrre',
    'fysik',
    'fædre',
    'fælde',
    'fælle',
    'færre',
    'føder',
    'fødte',
    'føjer',
    'føler',
    'føles',
    'følge',
    'følte',
    'fører',
    'føres',
    'førte',
    'fåtal',
    'gabon',
    'gaden',
    'gader',
    'gager',
    'galop',
    'gamle',
    'gamma',
    'gange',
    'gangs',
    'garde',
    'gauss',
    'gaven',
    'gaver',
    'gebyr',
    'gedde',
    'geder',
    'gemal',
    'gemme',
    'gemte',
    'gener',
    'genre',
    'georg',
    'gerda',
    'gerne',
    'gerti',
    'gevær',
    'ghana',
    'gider',
    'gifte',
    'gires',
    'gisne',
    'given',
    'giver',
    'gives',
    'givet',
    'givne',
    'gjort',
    'glade',
    'glemt',
    'glenn',
    'glide',
    'glimt',
    'glæde',
    'gnide',
    'gnier',
    'godes',
    'gokke',
    'gotik',
    'grads',
    'grams',
    'grand',
    'grant',
    'grata',
    'grave',
    'grete',
    'greve',
    'gribe',
    'grimt',
    'grise',
    'groft',
    'grove',
    'grund',
    'græsk',
    'grønt',
    'gubbe',
    'guden',
    'guder',
    'guide',
    'gules',
    'gummi',
    'gurli',
    'gylle',
    'gynge',
    'gælde',
    'gængs',
    'gætte',
    'gøder',
    'gøres',
    'gøsta',
    'gåsen',
    'habil',
    'habit',
    'hader',
    'hades',
    'hadet',
    'haiti',
    'hajen',
    'hajer',
    'hakke',
    'halen',
    'haler',
    'halve',
    'halvt',
    'hanke',
    'hanne',
    'harem',
    'harly',
    'harpe',
    'harry',
    'harve',
    'hasen',
    'hasse',
    'haste',
    'hauge',
    'havde',
    'haven',
    'haver',
    'haves',
    'havet',
    'havne',
    'havre',
    'hedde',
    'heden',
    'heder',
    'hejre',
    'hejsa',
    'hekse',
    'helbo',
    'helen',
    'heles',
    'helge',
    'helle',
    'helme',
    'helse',
    'helst',
    'helte',
    'hende',
    'henna',
    'henne',
    'henri',
    'henry',
    'hente',
    'heppe',
    'heraf',
    'herom',
    'herpå',
    'herre',
    'hersk',
    'heste',
    'hevet',
    'hidse',
    'higen',
    'hilse',
    'hinde',
    'hindu',
    'hjalp',
    'hjelm',
    'hjort',
    'hjælp',
    'hobby',
    'hoben',
    'hober',
    'hofte',
    'holde',
    'holdt',
    'holte',
    'hoppe',
    'hoste',
    'hotel',
    'hoved',
    'hoves',
    'huden',
    'huder',
    'hugge',
    'hulen',
    'human',
    'humor',
    'humør',
    'hunde',
    'hurra',
    'huset',
    'huske',
    'husly',
    'hvalp',
    'hvede',
    'hvert',
    'hverv',
    'hvide',
    'hvidt',
    'hvile',
    'hvori',
    'hvælv',
    'hybel',
    'hyben',
    'hygge',
    'hykle',
    'hylde',
    'hymen',
    'hymne',
    'hyrde',
    'hyret',
    'hytte',
    'hæder',
    'hæfte',
    'hægte',
    'hændt',
    'hænge',
    'hængt',
    'hæren',
    'hærge',
    'hævde',
    'hæver',
    'hæves',
    'hævne',
    'højde',
    'højer',
    'højne',
    'højre',
    'højst',
    'hørby',
    'hører',
    'høres',
    'hørte',
    'høste',
    'håber',
    'håbet',
    'hårde',
    'hårdt',
    'håret',
    "ibm's",
    'ideal',
    'ideel',
    'ideen',
    'ideer',
    'idiom',
    'idiot',
    'ifald',
    'ihjel',
    'ikons',
    'ilden',
    'ilder',
    'ilten',
    'iltet',
    'image',
    'imens',
    'immun',
    'indad',
    'indbo',
    'inden',
    'indgå',
    'indse',
    'indså',
    'indvi',
    'infam',
    'ingen',
    'inger',
    'input',
    'intim',
    'iraks',
    'ironi',
    'irske',
    'jacob',
    'jager',
    'jakke',
    'jakob',
    'jamen',
    'james',
    'japan',
    'jeget',
    'jeppe',
    'jeres',
    'jesse',
    'jesus',
    'jeton',
    'jette',
    'jimmy',
    'joens',
    'johan',
    'joker',
    'jolle',
    'jonas',
    'jorde',
    'jubel',
    'judas',
    'juice',
    'julen',
    'jules',
    'julia',
    'junke',
    'juvel',
    'jyske',
    'jæger',
    'jætte',
    'jævne',
    'jævnt',
    'kaare',
    'kabel',
    'kaffe',
    'kager',
    'kakao',
    'kalde',
    'kaldt',
    'kamel',
    'kanal',
    'kande',
    'kapel',
    'kappe',
    'kapre',
    'karby',
    'karen',
    'karin',
    'karry',
    'kasse',
    'kaste',
    'kbyte',
    'kedet',
    'keith',
    'kelly',
    'kende',
    'kendt',
    'kenya',
    'kerne',
    'khmer',
    'kigge',
    'kikke',
    'kilde',
    'kiosk',
    'kirke',
    'kiste',
    'kjeld',
    'klage',
    'klamt',
    'klang',
    'klare',
    'klart',
    'klaus',
    'klavs',
    'klode',
    'kloen',
    'kloge',
    'klogt',
    'klædt',
    'kløen',
    'kløft',
    'knapt',
    'knubs',
    'koben',
    'koble',
    'kobra',
    'koden',
    'koder',
    'kodes',
    'kodet',
    'kofod',
    'kofte',
    'koges',
    'koket',
    'kolde',
    'koldt',
    'kolon',
    'komma',
    'komme',
    'konge',
    'konti',
    'konto',
    'koral',
    'korea',
    'korps',
    'korte',
    'koste',
    'kraft',
    'krage',
    'kreol',
    'krige',
    'krise',
    'kroen',
    'kroge',
    'krogh',
    'krone',
    'kryds',
    'krypt',
    'kræft',
    'kræve',
    'kugle',
    'kujon',
    'kulde',
    'kunde',
    'kunne',
    'kunst',
    'kurer',
    'kurie',
    'kurve',
    'kusse',
    'kvast',
    'kæder',
    'kæmpe',
    'køber',
    'købes',
    'købet',
    'købte',
    'kødet',
    'køler',
    'kølle',
    'kører',
    'køres',
    'køret',
    'kørte',
    'labil',
    'lader',
    'ladet',
    'lagde',
    'lagen',
    'lager',
    'lagre',
    'laila',
    'lande',
    'lands',
    'lange',
    'langs',
    'langt',
    'lanka',
    'lanse',
    'lappe',
    'larry',
    'laser',
    'lasse',
    'latin',
    'laver',
    'laves',
    'lavet',
    'leder',
    'ledes',
    'ledet',
    'ledig',
    'ledte',
    'legen',
    'leger',
    'lejre',
    'leone',
    'leret',
    'lersø',
    'lette',
    'lever',
    'levet',
    'levne',
    'liden',
    'liget',
    'ligge',
    'ligne',
    'likør',
    'lilla',
    'lille',
    'limes',
    'linds',
    'linen',
    'liner',
    'lines',
    'linet',
    'linie',
    'linje',
    'linse',
    'liste',
    'liter',
    'livet',
    'logge',
    'logik',
    'lokal',
    'lokke',
    'lokum',
    'lomme',
    'longe',
    'lords',
    'louis',
    'loven',
    'lover',
    'lovet',
    'loyal',
    'lucia',
    'lufts',
    'lugte',
    'lukke',
    'lurer',
    'lyden',
    'lyder',
    'lydig',
    'lygte',
    'lykke',
    'lynet',
    'lynne',
    'lyrik',
    'lyser',
    'lyset',
    'lysår',
    'lytte',
    'læder',
    'lægge',
    'lækre',
    'længe',
    'lærde',
    'læren',
    'lærer',
    'læres',
    'lærte',
    'læser',
    'læses',
    'læste',
    'løben',
    'løber',
    'løbes',
    'løbet',
    'løfte',
    'løkke',
    'løsen',
    'løser',
    'løses',
    'løste',
    'låget',
    'lånes',
    'låsen',
    'låser',
    'låses',
    'låste',
    'macro',
    'madam',
    'maden',
    'magen',
    'mager',
    'magis',
    'magma',
    'major',
    'malet',
    'malmø',
    'malta',
    'mands',
    'mange',
    'manus',
    'mappe',
    'maria',
    'marsk',
    'marts',
    'maske',
    'masse',
    'maxim',
    'mbyte',
    'media',
    'medie',
    'medio',
    'megen',
    'meget',
    'mejer',
    'melde',
    'meldt',
    'melet',
    'melis',
    'mener',
    'menes',
    'mente',
    'messe',
    'meste',
    'metal',
    'metan',
    'meter',
    'mette',
    'meyer',
    'mider',
    'midte',
    'milde',
    'miljø',
    'mille',
    'milos',
    'mimik',
    'minde',
    'minus',
    'minut',
    'miste',
    'model',
    'modem',
    'moden',
    'modes',
    'modne',
    'modul',
    'modus',
    'moral',
    'moras',
    'moret',
    'mosen',
    'moses',
    'motiv',
    'motor',
    'motto',
    'mulig',
    'munde',
    'munke',
    'munks',
    'musik',
    'myrra',
    'myten',
    'myter',
    'mærke',
    'møder',
    'mødes',
    'mødet',
    'mødte',
    'mørke',
    'mørkt',
    'måden',
    'måder',
    'måler',
    'målet',
    'måløv',
    'måned',
    'månen',
    'måske',
    'måtte',
    'naivt',
    'narre',
    'natur',
    'navne',
    'nedad',
    'nedre',
    'nemme',
    'nepal',
    'netop',
    'netto',
    'neucc',
    'niche',
    'niece',
    'niels',
    'niger',
    'nital',
    'nobel',
    'nodes',
    'nogen',
    'noget',
    'nogle',
    'nonne',
    'norge',
    'notat',
    'noter',
    'novra',
    'numre',
    'nutid',
    'nyder',
    'nyere',
    'nylig',
    'nylon',
    'nytte',
    'nytår',
    'næppe',
    'nærer',
    'næres',
    'nærme',
    'nærum',
    'næste',
    'næven',
    'nævne',
    'nævnt',
    'nøgen',
    'nøgle',
    'nøgne',
    'nøjes',
    'nørre',
    'nåede',
    'ocean',
    'odden',
    'odder',
    'odens',
    'offer',
    'ofrer',
    'ofret',
    'okker',
    'oktan',
    'oline',
    'olsen',
    'omega',
    'omegn',
    'omgås',
    'omløb',
    'omsat',
    'onkel',
    'opbyg',
    'opdel',
    'opera',
    'opfat',
    'opgør',
    'ophav',
    'ophør',
    'opium',
    'oplag',
    'oplys',
    'oplæg',
    'opnår',
    'opnås',
    'opret',
    'oprør',
    'opsat',
    'opsig',
    'opstå',
    'opsøg',
    'optag',
    'optik',
    'optog',
    'optæl',
    'opøve',
    'ordet',
    'ordne',
    'ordre',
    'organ',
    'orker',
    'orlon',
    'oscar',
    'osede',
    'osten',
    'ovale',
    'oveni',
    'pakke',
    'palle',
    'panda',
    'panik',
    'papir',
    'parat',
    'paris',
    'parre',
    'parti',
    'party',
    'passe',
    'pasta',
    'patos',
    'patte',
    'paulo',
    'pause',
    'paven',
    "pc'er",
    'peber',
    'peder',
    'peger',
    'peget',
    'pelle',
    'penge',
    'perle',
    'perry',
    'peter',
    'piano',
    'pigen',
    'piger',
    'piges',
    'pikke',
    'pilen',
    'pilot',
    'pinde',
    'pines',
    'pinse',
    'pippe',
    'pirat',
    'pirre',
    'piske',
    'plade',
    'plads',
    'plage',
    'plane',
    'plant',
    'plast',
    'plato',
    'pleje',
    'pligt',
    'pløje',
    'poesi',
    'point',
    'polar',
    'polen',
    'polet',
    'polsk',
    'porto',
    'ports',
    'poser',
    'potte',
    'prima',
    'prins',
    'print',
    'prosa',
    'præge',
    'præst',
    'prøve',
    'psyke',
    'pulte',
    'punkt',
    'puppe',
    'putte',
    'pæleg',
    'pølse',
    'påkær',
    'pålæg',
    'påske',
    'påstå',
    'quasi',
    'rabat',
    'racer',
    'races',
    'radio',
    'rakte',
    'rally',
    'ralph',
    'ramme',
    'rampe',
    'ranet',
    'rangs',
    'ranke',
    'rater',
    'ravns',
    'realt',
    'rebet',
    'recau',
    'recks',
    'recku',
    'redde',
    'reelt',
    'regel',
    'regne',
    'reich',
    'rejse',
    'rende',
    'renes',
    'rense',
    'rente',
    'rette',
    'retur',
    'rider',
    'riger',
    'riget',
    'rikke',
    'ringe',
    'rings',
    'riste',
    'river',
    'robot',
    'roden',
    'rodet',
    'roere',
    'roger',
    'rolle',
    'roman',
    'roses',
    'rotte',
    'rouge',
    'round',
    'rubin',
    'rulle',
    'rumme',
    'runde',
    'rundt',
    'runer',
    'runes',
    'rydde',
    'ryger',
    'ryges',
    'rygte',
    'rykke',
    'rytme',
    'række',
    'røber',
    'røbet',
    'røgen',
    'røget',
    'rønne',
    'rørby',
    'rører',
    'røret',
    'røven',
    'røver',
    'råber',
    'råbte',
    'råder',
    'rådet',
    'råhed',
    'sachs',
    'sadat',
    'safir',
    'sagde',
    'sagen',
    'sager',
    'saldo',
    'salgs',
    'salme',
    'salte',
    'salut',
    'samle',
    'samme',
    'samoa',
    'sande',
    'sandt',
    'sange',
    'sankt',
    'sanse',
    'sarah',
    'sarte',
    'satse',
    'satte',
    'sauce',
    'saudi',
    'saver',
    'saves',
    'scene',
    'score',
    'sekel',
    'selde',
    'senat',
    'sende',
    'sendt',
    'senge',
    'sengs',
    'senil',
    'serie',
    'sfære',
    'shows',
    'sidde',
    'siden',
    'sider',
    'sides',
    'sidst',
    'siems',
    'siger',
    'siges',
    'sigga',
    'sigte',
    'sikre',
    'silke',
    'simon',
    'sinde',
    'sines',
    'siver',
    'sjove',
    'sjovt',
    'sjæle',
    'skabe',
    'skabt',
    'skade',
    'skaft',
    'skakt',
    'skala',
    'skare',
    'skarp',
    'skede',
    'skeen',
    'skema',
    'skete',
    'skibe',
    'skift',
    'skilt',
    'skind',
    'skive',
    'skjul',
    'skole',
    'skots',
    'skrab',
    'skrap',
    'skrat',
    'skrev',
    'skrig',
    'skrin',
    'skriv',
    'skrog',
    'skrue',
    'skråt',
    'skude',
    'skyld',
    'skægt',
    'skære',
    'skærm',
    'skøde',
    'skønt',
    'skøre',
    'skåle',
    'slags',
    'slave',
    'slige',
    'sligt',
    'slået',
    'smage',
    'smagt',
    'smalt',
    'smart',
    'smede',
    'smidt',
    'smith',
    'smukt',
    'smule',
    'smøre',
    'snaps',
    'snart',
    'snige',
    'snore',
    'snuse',
    'snyde',
    'snydt',
    'sofie',
    'solen',
    'soler',
    'solgt',
    'solid',
    'sonja',
    'sonny',
    'sorte',
    'sover',
    'spand',
    'spare',
    'sperm',
    'spids',
    'spise',
    'spist',
    'splid',
    'split',
    'spole',
    'sport',
    'spray',
    'sprit',
    'sprog',
    'spurv',
    'spænd',
    'spørg',
    'stald',
    'stand',
    'stang',
    'stank',
    'start',
    'stave',
    'stede',
    'steen',
    'stege',
    'stegt',
    'stemt',
    'steve',
    'stien',
    'stier',
    'stift',
    'stime',
    'stole',
    'stolt',
    'store',
    'stork',
    'storm',
    'stort',
    'straf',
    'stram',
    'streg',
    'strid',
    'strip',
    'stræk',
    'strøm',
    'stuen',
    'styre',
    'stænk',
    'stærk',
    'støde',
    'stødt',
    'sudan',
    'suite',
    'super',
    'suppe',
    'susan',
    'susse',
    'sutte',
    'svagt',
    'svamp',
    'svane',
    'svare',
    'svend',
    'svien',
    'svine',
    'svovl',
    'sværd',
    'svære',
    'svært',
    'svæve',
    'syden',
    'sydpå',
    'synes',
    'synet',
    'synge',
    'syren',
    'sælge',
    'sænke',
    'sæson',
    'sætte',
    'søgen',
    'søger',
    'søges',
    'søgte',
    'søjle',
    'søren',
    'sørge',
    'sådan',
    'såret',
    'såvel',
    'tabel',
    'taber',
    'tabet',
    'tabte',
    'tager',
    'tages',
    'taget',
    'takke',
    'talen',
    'taler',
    'tales',
    'talte',
    'tanke',
    'tappe',
    'tapre',
    'taste',
    'tasts',
    'tavse',
    'teddy',
    'tegne',
    'tehus',
    'tekla',
    'tekst',
    'telex',
    'temas',
    'tempi',
    'tempo',
    'teori',
    'terne',
    'terre',
    'teste',
    'texas',
    'thule',
    'tiara',
    'tiden',
    'tider',
    'tiger',
    'timen',
    'timer',
    'times',
    'tinge',
    'tings',
    'tisse',
    'titan',
    'titel',
    'tjene',
    'tjent',
    'tjære',
    'tobak',
    'toget',
    'tokyo',
    'tolke',
    'tomas',
    'tomat',
    'tomme',
    'tommy',
    'toner',
    'tonga',
    'tonny',
    'total',
    'trace',
    'trane',
    'trang',
    'trans',
    'trier',
    'trist',
    'trods',
    'troen',
    'troet',
    'trold',
    'trone',
    'truck',
    'truer',
    'træde',
    'træer',
    'træet',
    'træne',
    'trøje',
    'trådt',
    'tuber',
    'tudse',
    'tumle',
    'tunet',
    'tunge',
    'tungt',
    'turbo',
    'turde',
    'turen',
    'tvang',
    'tvist',
    'tvivl',
    'tværs',
    'tweed',
    'tyder',
    'tykke',
    'tynde',
    'typen',
    'typer',
    'tyske',
    'tyven',
    'tælle',
    'tæmme',
    'tænde',
    'tændt',
    'tænke',
    'tænkt',
    'tæppe',
    'tærte',
    'tætte',
    'tøjet',
    'tøjle',
    'tømme',
    'tønde',
    'tørre',
    'tørst',
    'tåler',
    'tårer',
    'udbud',
    'uddyb',
    'udfor',
    'udfri',
    'udfør',
    'udgav',
    'udgør',
    'udgår',
    'udkig',
    'udkom',
    'udløb',
    'udlån',
    'udpeg',
    'udsat',
    'udsyn',
    'udtag',
    'udøde',
    'udøve',
    'uenig',
    'ugens',
    'ugers',
    'ugift',
    'uheld',
    'uhyre',
    'ulige',
    'ulrik',
    'ulyst',
    'uløst',
    'umage',
    'under',
    'undgå',
    'undre',
    'undse',
    'unges',
    'unikt',
    'union',
    'unåde',
    'urter',
    'urtid',
    'usagt',
    'usand',
    'utopi',
    'uøvet',
    'valby',
    'valgt',
    'vandt',
    'vaner',
    'varde',
    'varen',
    'varer',
    'varet',
    'varia',
    'varig',
    'varme',
    'varmt',
    'vasal',
    'vaske',
    'vegne',
    'vejen',
    'vejer',
    'vejle',
    'vejrs',
    'vende',
    'vendt',
    'vente',
    'viden',
    'video',
    'vides',
    'vidne',
    'vidst',
    'viger',
    'viggo',
    'vilde',
    'vildt',
    'vilje',
    'ville',
    'vinde',
    'vinen',
    'vinke',
    'vippe',
    'viril',
    'virke',
    'virum',
    'viser',
    'vises',
    'visne',
    'visse',
    'viste',
    'vitae',
    'vital',
    'vodka',
    'vogne',
    'vogte',
    'vokal',
    'vokse',
    'volde',
    'volta',
    'vores',
    'vrede',
    'vredt',
    'vrøvl',
    'vægge',
    'vække',
    'vækst',
    'vælge',
    'vælte',
    'værdi',
    'været',
    'værks',
    'værne',
    'værre',
    'værst',
    'væsen',
    'væske',
    'vævet',
    'våben',
    'vågen',
    'vågne',
    'wales',
    'wandy',
    'watts',
    'willi',
    'willy',
    'withs',
    'xviii',
    'ydmyg',
    'yemen',
    'yndig',
    'yngre',
    'zaire',
    'zelot',
    'zonen',
    'åbent',
    'åbner',
    'åbnes',
    'åbnet',
    'årene',
    'årets',
    'årlig',
    'årsag',
    'øgede',
    'øjner',
    'ømhed',
    'ønske',
    'østen',
    'østre',
    'øvede',
    'æbler',
    'æblet',
    'ældes',
    'ældre',
    'ændre',
    'ærede',
    'ærter',
];
